# Generated by Django 4.2 on 2023-04-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildsteppe', '0006_trail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trail',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
