# Generated by Django 4.2 on 2023-04-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildsteppe', '0007_alter_trail_distance_alter_trail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='trail',
            name='difficulty_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wildsteppe.difficulty_level'),
        ),
    ]
