# Generated by Django 4.2 on 2023-04-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildsteppe', '0008_difficulty_level_trail_difficulty_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Difficulty_Level',
            new_name='Difficulty',
        ),
        migrations.RenameField(
            model_name='trail',
            old_name='difficulty_level',
            new_name='difficulty',
        ),
    ]
