# Generated by Django 4.2 on 2023-04-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildsteppe', '0009_rename_difficulty_level_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='activities',
            field=models.ManyToManyField(help_text='Select Activity', to='wildsteppe.activity'),
        ),
    ]
