# Generated by Django 4.2 on 2023-04-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildsteppe', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
